const quoteList = [
    'Scott, what team is Yao Ming on?',
    'The Cubs are a New York team because I say so',
    'The Broncos are from the Bronx',
,   'The Knicks aren’t spelled with a k and they’re a baseball team stupid',
    'shrek ',
    'dexter',
    'frozen',
    'rocky',
    'dune',
    'moana',
    'titanic',
    'inception',
    'sharknado',
    'mammamia',
    'jumanji',
    'snowwhite',
    'theoffice',
    'fightclub',
    'friends',
    'greenbook',
    'velocipastor',
    'adventuretime',
    'haroldandkumargotowhitecastle',
    'supernatural',
    'thewalkingdead',
    'invincible',
    'crouchingtigerhiddendragon',
    'samuraijack',
    'interstellar',
    'montypythonandtheholygrail'
]